- type: job
  id: AtmosphericTechnician
  name: job-name-atmostech
  description: job-description-atmostech
  playTimeTracker: JobAtmosphericTechnician
  #requirements: # Umbra: Use Umbra Roletimers over Wizden.
  #- !type:DepartmentTimeRequirement
  #  department: Engineering
  #  time: 9000 #2.5 hrs
  startingGear: AtmosphericTechnicianGear
  icon: "JobIconAtmosphericTechnician"
  supervisors: job-supervisors-ce
  access:
  - Maintenance
  - Engineering
  - External
  - Atmospherics
  special:
  - !type:GiveItemOnHolidaySpecial
    holiday: FirefighterDay
    prototype: FireAxe

- type: startingGear
  id: AtmosphericTechnicianGear
  equipment:
#    eyes: ClothingEyesGlassesMeson # CD
    id: AtmosPDA
    belt: ClothingBeltUtilityEngineering
    ears: ClothingHeadsetEngineering
  #storage:
    #back:
    #- Stuff

- type: chameleonOutfit
  id: AtmosphericTechnicianChameleonOutfit
  job: AtmosphericTechnician
  equipment:
    head: ClothingHeadHelmetAtmosFire
    mask: ClothingMaskGasAtmos
    neck: ClothingNeckScarfStripedLightBlue
    outerClothing: ClothingOuterSuitAtmosFire
    gloves: ClothingHandsGlovesColorYellow
